name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Change directory to src and compile Java application
        run: |
          cd src
          javac MethodClass.java HelloDocker.java

      - name: Change directory to src and create JAR file
        run: |
          cd src
          jar cfm HelloDocker.jar Manifest.txt HelloDocker.class MethodClass.class

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          push: true
          tags: mario7400/hellodocker-java:latest
